### ISSUE TITLE
Ajouter critère de recherche : surface min (habitable)

### ISSUE THREAD

**Issue by markotxe** [pgrange/risno#22]

**Comment by pgrange** [comment]
C'est une demande qui revient régulièrement. Je laisse cette issue ouverte pour tracer.

Cependant c'est un chantier assez lourd. Je ne vais pas l'entamer maintenant, j'ai d'autres issues que je considère plus prioritaires pour le moment.

A suivre...

**Comment by pgrange** [comment]
Je pense que le problème sera corrigé par #33
