### ISSUE TITLE
Update ansible configuration to support Docker deployment

### ISSUE THREAD

**Issue by nlamirault** [pgrange/risno#26]
Ansible can manage Docker containers [1]. Update ansible setup to deploy Risno using Docker images.

[1] : http://docs.ansible.com/docker_module.html

**Comment by pgrange** [comment]
Risno already use this to set up elasticsearch docker configuration in production. See in https://github.com/pgrange/risno/blob/master/ansible/roles/elastic/tasks/main.yml

- name: start elasticsearch database
  docker:
    image: pgrange/elasticsearch
    ports: 9200:9200 
    volumes:
    - '/var/opt/risno/elastic-storage/log/:/var/log/elasticsearch'
    - '/var/opt/risno/elastic-storage/data/:/var/lib/elasticsearch'

**Comment by pgrange** [comment]
Since your pul request #19, I am playing with compose and trying to evolve ansible configuration so that we can describe containers with compose and, either deploy this descritpion with ansible, or directly run this description with compose in development environment.
