### ISSUE TITLE
Manage other French regions

### ISSUE THREAD

**Issue by nlamirault** [pgrange/risno#7]
Could you add support for other French regions (like Midi-Pyrénées).

**Comment by pgrange** [comment]
First, we have to fix #10.

Then one can add any new french region by :
1. configuring region information in slurp/config.json
2. add region in cronjob here : ansible/roles/risno/tasks/main.yml

**Comment by pgrange** [comment]
Il ne reste plus qu'à configurer dans slurp/config.json les infos pour la nouvelle région puis à ajouter sa récupération dans la crontab en ajoutant dans ansible/roles/risno/tasks/main.yml une section de la forme :

- name: crontab to fetch new pubs
  cron: name="fetch pubs from sites" cron_file=risno user=risno
        hour=11 minute=1
        job="node /opt/risno/slurp/fetch_sites aquitaine >>/var/opt/risno/fetch.log 2>&1"

**Comment by pgrange** [comment]
Midi-Pyrénées ajoutée.

@nlamirault tu peux tester à partir de demain pour vérifier que tu vois bien apparaître des annonces en Midi-Pyrénées.

Il me reste à documenter l'ajout d'une nouvelle région avant de fermer cette issue.
